#!/bin/sh

function draw {
	if [ -f "$1" ] && [ -n "$DISPLAY" ] && command -V ueberzug
	then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > /tmp/ueberzug
	fi
}

case "$(file --dereference --brief --mime-type -- "$1")" in
	application/x-tar) tar tf "$1";;
	application/gzip) tar tzf "$1";;
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	text/troff) man -l "$1" | col -b ;;
	image/*) mediainfo "$1";;
	audio/*|video/*) mediainfo "$1";;
	*/pdf) pdftotext "$1" - ;;
	text/* | */xml | application/json) @LF_HIGHLIGHT@ "$1";;
	*) @LF_HIGHLIGHT@ "$1";;
esac
